name: CI-Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=15.2,name=iPhone 13']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          xcodebuild clean build -project AuthSDK.xcodeproj -scheme AuthSDK -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
      - name: Test
        run: |
          xcodebuild test \
-project AuthSDK.xcodeproj \
-scheme AuthSDKTests \
-destination 'platform=iOS Simulator,name=iPhone 13,OS=15.2'
        env: 
         destination: ${{ matrix.destination }}
